# baseURL = '/website.mieszkancy-bgw/'
baseURL = '/'
defaultContentLanguage = 'pl'
languageCode = 'pl-PL'
title = 'Mieszkańcy Bohaterów Getta Warszawskiego'

[params]
    titleShort = 'Mieszkańcy BGW'
    subtitle = 'o linii tramwajowej Gdańsk Południe - Wrzeszcz'

# chronology
# https://codepen.io/MarkBoots/pen/OJOqNyB