baseURL = 'https://mieszkancybgw.pl/'
defaultContentLanguage = 'pl'
languageCode = 'pl-PL'
title = 'Mieszkańcy Bohaterów Getta Warszawskiego'

[params]
    titleShort = 'Mieszkańcy BGW'
    subtitle = 'o linii tramwajowej Gdańsk Południe - Wrzeszcz'

[params.social]
description = "Mieszkańcy Bohaterów Getta o inwestycji tramwajowej GP-W."

[params.social.opengraph]
fb = "img/social/bgw-opengraph.jpg"
twitter = "img/social/bgw-opengraph-sq.jpg" 

# chronology
# https://codepen.io/MarkBoots/pen/OJOqNyB